WiredBrainCoffeeAdmin/Components/ProductListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WiredBrainCoffeeAdmin.Data.Repositories;

namespace WiredBrainCoffeeAdmin.Components;

public class ProductListViewComponent : ViewComponent
{
    private readonly IProductRepository _repository;

    public ProductListViewComponent(IProductRepository repository)
    {
        _repository = repository;
    }

    public IViewComponentResult Invoke(int count)
    {
        var itens = count > 0 ?
            _repository.GetAll().Take(count).ToList() :
            _repository.GetAll();

        return View(itens);
    }
}

WiredBrainCoffeeAdmin/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WiredBrainCoffeeAdmin.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WiredBrainCoffeeAdmin/Pages/Help.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WiredBrainCoffeeAdmin.Data.Models;
using WiredBrainCoffeeAdmin.HttpServices;

namespace WiredBrainCoffeeAdmin.Pages;

public class HelpModel : PageModel
{
    [BindProperty]
    public HelpTicket NewTicket { get; set; }
    public List<HelpTicket> HelpTickets { get; set; }
    public string ResponseMessage { get; set; }

    private readonly ITicketService _ticketService;

    public HelpModel(ITicketService ticketService)
    {
        _ticketService = ticketService;
    }

    public async Task<IActionResult> OnGet()
    {
        HelpTickets = await _ticketService.GetAll();

        return Page();
    }

    public async Task<IActionResult> OnPost()
    {
        ResponseMessage = await _ticketService.Add(NewTicket);
        HelpTickets = await _ticketService.GetAll();
        return Page();
    }
}

WiredBrainCoffeeAdmin/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;
using WiredBrainCoffeeAdmin.Data.Models;

namespace WiredBrainCoffeeAdmin.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IHttpClientFactory _factory;

        public List<SurveyItem> SurveyItems { get; set; }
        public IDictionary<string, string> OrderStats { get; set; }
        public IndexModel(ILogger<IndexModel> logger,
            IHttpClientFactory factory)
        {
            _logger = logger;
            _factory = factory;
        }

        public async Task<IActionResult> OnGet()
        {
            var rawJson = System.IO.File.ReadAllText("wwwroot/SampleData/survey.json");

            SurveyItems = JsonSerializer.Deserialize<List<SurveyItem>>(rawJson);

            var client = _factory.CreateClient();
            var response = await client
                .GetAsync("https://wiredbraincoffeeadmin.azurewebsites.net/api/orderStats");

            var responseData = await response.Content.ReadAsStringAsync();

            OrderStats = JsonSerializer.Deserialize<IDictionary<string, string>>(responseData);

            return Page();
        }
    }
}

WiredBrainCoffeeAdmin/Pages/products/AddProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WiredBrainCoffeeAdmin.Data;
using WiredBrainCoffeeAdmin.Data.Models;
using WiredBrainCoffeeAdmin.Data.Repositories;

namespace WiredBrainCoffeeAdmin.Pages.products;

public class AddProductModel : PageModel
{
    private readonly IProductRepository _repository;
    private readonly IWebHostEnvironment _webEnvironment;

    [BindProperty]
    public Product NewProduct { get; set; }

    public AddProductModel(
        IProductRepository _repository,
        IWebHostEnvironment webEnvironment)
    {
        this._repository = _repository;
        _webEnvironment = webEnvironment;
    }

    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPost()
    {
        if (!ModelState.IsValid) return Page();
        
        await UploadImage(NewProduct.Upload);

        NewProduct.Created = DateTime.Now;

        _repository.Create(NewProduct);

        return RedirectToPage("ViewAllProducts");
    }

    private async Task UploadImage(IFormFile image)
    {
        if (image is not null)
        {
            NewProduct.ImageFileName = image.FileName;

            var filePath = Path
                .Combine(_webEnvironment.ContentRootPath, "wwwroot/images/menu", NewProduct.ImageFileName);

            using var fileStream = new FileStream(filePath, FileMode.Create);
            await NewProduct.Upload.CopyToAsync(fileStream);
        }
    }
}

WiredBrainCoffeeAdmin/Pages/products/EditProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WiredBrainCoffeeAdmin.Data.Models;
using WiredBrainCoffeeAdmin.Data.Repositories;

namespace WiredBrainCoffeeAdmin.Pages.products;

public class EditProductModel : PageModel
{
    private readonly IProductRepository _repository;
    private readonly IWebHostEnvironment _webEnvironment;

    public EditProductModel(
        IProductRepository repository,
        IWebHostEnvironment webEnvironment)
    {
        _repository = repository;
        _webEnvironment = webEnvironment;
    }

    [BindProperty]
    public Product EditProduct { get; set; }

    [FromRoute]
    public int Id { get; set; }

    public void OnGet()
    {
        EditProduct = _repository.GetById(Id);
    }

    public async Task<IActionResult> OnPostEdit()
    {
        if (!ModelState.IsValid) return Page();

        if (EditProduct.Upload != null)
        {
            await UploadImage(EditProduct.Upload);
        }

        _repository.Update(EditProduct);

        return RedirectToPage("ViewAllProducts");
    }

    public IActionResult OnPostDelete()
    {
        _repository.Delete(EditProduct.Id);
        return RedirectToPage("ViewAllProducts");
    }

    private async Task UploadImage(IFormFile image)
    {
        EditProduct.ImageFileName = image.FileName;

        var filePath = Path
            .Combine(_webEnvironment.ContentRootPath, "wwwroot/images/menu", EditProduct.ImageFileName);

        using var fileStream = new FileStream(filePath, FileMode.Create);
        await EditProduct.Upload.CopyToAsync(fileStream);
    }
}

WiredBrainCoffeeAdmin/Pages/products/ViewAllProducts.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using WiredBrainCoffeeAdmin.Data.Models;
using WiredBrainCoffeeAdmin.Data.Repositories;

namespace WiredBrainCoffeeAdmin.Pages.products;

public class ViewAllProductsModel : PageModel
{
    private readonly IProductRepository _repository;
    public List<Product> Products { get; set; }

    public ViewAllProductsModel(IProductRepository repository)
    {
        _repository = repository;
    }

    public void OnGet()
    {
        Products = _repository.GetAll();
    }
}

WiredBrainCoffeeAdmin/Pages/Help.cshtml
@page "/help"
@model WiredBrainCoffeeAdmin.Pages.HelpModel
@{
}

<h1>Service Desk</h1>
<hr />

@if (!string.IsNullOrEmpty(Model.ResponseMessage))
{
    <p class="alert alert-info">@Model.ResponseMessage</p>
}

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                Request Help
            </div>
            <div class="card-body">
                <h5 class="card-title">Contact our IT Team</h5>
                <p class="card-text">Having an issue with the site? Let us know!</p>
                <form method="post">
                    <div class="mb-3">
                        <label asp-for="NewTicket.Title">Title</label>
                        <input asp-for="NewTicket.Title" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <label asp-for="NewTicket.Description">Description</label>
                        <textarea asp-for="NewTicket.Description" class="form-control"></textarea>
                    </div>
                    <button type="submit" class="btn btn-success">Submit</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <h2>Current Issues</h2>
        <hr />
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var ticket in Model.HelpTickets)
                {
                    <tr>
                        <td>@ticket.Id</td>
                        <td>@ticket.Title</td>
                        <td>@ticket.Description</td>
                        <td>@ticket.Status</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section RightFooter {
    <p>Call us at: 123-456-789</p>
    <p>Hours of operation: 9am to 4pm</p>
}

WiredBrainCoffeeAdmin/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="container-fluid dashboard">
    <h1 class="h2">Welcome to Wired Brain Coffee!</h1>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <h2>Latest Products</h2>

            @* @await Component.InvokeAsync("ProductList", new{count = 4})*@
            <vc:product-list count="5"></vc:product-list>

            <h2>Latest Survey Results</h2>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Question</th>
                        <th>Answer</th>
                    </tr>
                </thead>
                @foreach (var item in Model.SurveyItems)
                {
                    <tr>
                        <td>@item.Question</td>
                        <td>@item.Answer</td>
                    </tr>
                }
            </table>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    The Basics
                </div>
                <div class="card-body">
                    <p>Hello, today is @DateTime.Today.Date.ToString("MM/dd/yyyy").</p>
                    @{
                        var temperature = 55;
                    }
                    <p>The current temperature is @temperature degrees.</p>
                    @if (temperature < 60)
                    {
                        <p>We recommend a coat until it warms up</p>
                    }
                </div>
            </div>
            <partial name="_HelpWidget" />
            <h2>Weekly Stats</h2>
            <table class="table table-bordered table-striped">
                @foreach (var item in Model.OrderStats)
                {
                    <tr>
                        <td>@item.Key</td>
                        <td>@item.Value</td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

WiredBrainCoffeeAdmin/Pages/Shared/Components/ProductList/Default.cshtml
@using WiredBrainCoffeeAdmin.Data.Models
@model List<Product>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Image</th>
            <th>Name</th>
            <th>Category</th>
            <th>Price</th>
            <th>ShortDescription</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td><img src="~/images/menu/@item.ImageFileName" /></td>
                <td>@item.Name</td>
                <td>@item.Category</td>
                <td>@item.Price</td>
                <td>@item.ShortDescription</td>
                <td><a class="btn btn-success" asp-page="EditProduct" asp-route-id="@item.Id">Edit</a></td>
            </tr>
        }
    </tbody>
</table>

WiredBrainCoffeeAdmin/Pages/Shared/_HelpWidget.cshtml
<div class="card">
    <div class="card-header">
        Request Help
    </div>
    <div class="card-body">
        <h5 class="card-title">Contact our IT Team</h5>
        <p class="card-text">Having an issue with the site? Let us know!</p>
        <a asp-page="help" class="btn btn-success">Request Help</a>
    </div>
</div>

WiredBrainCoffeeAdmin/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WiredBrainCoffeeAdmin</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment names="Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WiredBrainCoffeeAdmin.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a asp-page="/Index" class="nav-link" aria-current="page">Dashboard</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Products
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                    <li><a asp-page="/products/viewallproducts" class="dropdown-item">View All</a></li>
                                    <li><a asp-page="/products/addproduct" class="dropdown-item">Add New</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link disabled">Orders (Coming soon)</a>
                            </li>
                            <li class="nav-item">
                                <a asp-page="/help" class="nav-link">Help</a>
                            </li>
                        </ul>
                    </div>
                    <a class="navbar-brand float-right">Wired Brain Coffee</a>
                </div>
            </nav>
        </header>
        <main>
            @RenderBody()
        </main>
        <footer>
            <div class="row">
                <div class="col-md-4">
                    <p>&copy; 2022 - WiredBrainCoffeeAdmin</p>
                    <img id="logo" src="~/images/wired-brain-coffee-logo.png" />
                </div>
                <div class="col-md-4">
                    <p>1234 Wired Brain Way</p>
                    <p>Awesome City, CA 55555</p>
                    <p>Phone: 555-123-4567</p>
                    <p>Fax: 555-123-4567</p>
                </div>
                <div class="col-md-4">
                    <div class="footer-pic">
                        @if (IsSectionDefined("RightFooter"))
                        {
                            @RenderSection("RightFooter")
                        }
                        else
                        {
                            <img src="~/images/menu/salad-house.png" />
                        }
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <partial name="_ValidationScriptsPartial" />

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WiredBrainCoffeeAdmin/Pages/products/AddProduct.cshtml
@page "/products/add"
@model WiredBrainCoffeeAdmin.Pages.products.AddProductModel
@{
}
<h1>Add New Product</h1>
<hr />

<div class="row">
    <div class="col-md-6">
        <partial name="_ProductForm" model="@Model.NewProduct" />
    </div>
    <div class="col-md-6">
        <partial name="_HelpWidget" />
    </div>
</div>

@section RightFooter {
    <img src="~/images/menu/cappucino.png" />
}

WiredBrainCoffeeAdmin/Pages/products/EditProduct.cshtml
@page "/products/edit/{id:int}"
@model WiredBrainCoffeeAdmin.Pages.products.EditProductModel
@{
}

<h1>Edit Product</h1>

<div class="row">
    <div class="col-md-6">
        <partial name="_ProductForm" model="@Model.EditProduct" />
    </div>
    <div class="col-md-6">
        <partial name="_HelpWidget" />
    </div>
</div>

WiredBrainCoffeeAdmin/Pages/products/ViewAllProducts.cshtml
@page "/products/all"
@model WiredBrainCoffeeAdmin.Pages.products.ViewAllProductsModel
@{
}
<h1>All Product</h1>
<hr />

<vc:product-list count="0"></vc:product-list>             

WiredBrainCoffeeAdmin/Pages/products/_ProductForm.cshtml
@using WiredBrainCoffeeAdmin.Data.Models
@model Product

<form method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All"></div>
    @if (ViewContext.RouteData.Values["id"] is not null)
    {
        <input type="hidden" asp-for="@Model.Id" />
    }
    <div class="mb-3">
        <label asp-for="@Model.Name">Name</label>
        <input asp-for="@Model.Name" class="form-control" />
        <span asp-validation-for="@Model.Name"></span>
    </div>
    <div class="mb-3">
        <label asp-for="@Model.ShortDescription">ShortDescription</label>
        <input asp-for="@Model.ShortDescription" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="@Model.Description">Description</label>
        <textarea asp-for="@Model.Description" class="form-control"></textarea>
    </div>
    <div class="mb-3">
        <label asp-for="@Model.Price">Price</label>
        <input asp-for="@Model.Price" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="@Model.Category"></label>
        <select asp-for="@Model.Category" class="form-control">
            <option value="Beverage">Beverage</option>
            <option value="Food">Food</option>
        </select>
    </div>
    @if (ViewContext.RouteData.Values["id"] is not null)
    {
        <div class="mb-3">
            <label asp-for="@Model.ImageFileName">Current Image</label>
            <input type="hidden" asp-for="@Model.ImageFileName" class="form-control" />
            <img src="~/images/menu/@Model.ImageFileName" />
        </div>
    }
    <div class="mb-3">
        <label asp-for="@Model.Upload">Image</label>
        <input asp-for="@Model.Upload" class="form-control" />
    </div>
    @if (ViewContext.RouteData.Values["id"] is not null)
    {
        <button asp-page-handler="edit" class="btn btn-success">Submit</button>
        <button asp-page-handler="delete" class="btn btn-danger float-end">Delete</button>
    }
    else
    {
        <button class="btn btn-success">Submit</button>
    }
</form>